[project]
name = "django-auth0"
version = "0.1.0b1"
description = "A django plugin to add auth0 OIDC authentication to django"
keywords = ["auth0", "django", "OIDC"]
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E.*"]
authors = [
    { name = "jojjo64", email = "rattan_stupse4d@icloud.com" }
]
maintainers = [
    { name = "jojjo64", email = "rattan_stupse4d@icloud.com" }
]
classifiers = [
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    "Development Status :: 4 - Beta",

    # License
    "License :: OSI Approved :: MIT License",

    # Indicate who your project is intended for
    "Intended Audience :: Developers",
    'Topic :: Internet :: WWW/HTTP',
    'Topic :: Internet :: WWW/HTTP :: Session',
    'Topic :: System :: Systems Administration :: Authentication/Directory',

    # Technical Stuff
    "Framework :: Django",
    "Framework :: Django :: 5.2",

    # Specify the Python versions you support here.
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.6.6",
]

[project.urls]
Repository = "https://github.com/jojjo64/django-auth0"

[tool.pytest.ini_options]
addopts = "--cov . -v --cov-report=xml"
python_files = ["tests.py", "test_*.py",  "*_tests.py"]

[tool.coverage.run]
include = ["src/django_auth0/*"]
omit = [
    "*/tests/*",
    "*/tests*",
    "*__init__*",
    ]
branch = true

[tool.coverage.report]
exclude_lines = ["pragma: no cover"]
show_missing = true
include = ["src/django_auth0/*"]
omit = [
    "*/tests/*",
    "*/tests*",
    "*__init__*",
    ]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/django_auth0"]

[dependency-groups]
dev = [
    "django>=5.2,<6.0",
    "genbadge[all]>=1.1.3",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.11.1",
    "ruff>=0.14.14",
]
